version: '3'
services:
    recipy:
      build:
        context: ./docker
        dockerfile: Dockerfile
        args:
          WWWGROUP: 'fmmi'
      extra_hosts:
        - 'host.docker.internal:host-gateway'
      ports:
        - '3520:80'
      environment:
        WWWUSER: 'fmmi'
        LARAVEL_SAIL: 1
        XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
        XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      volumes:
        - '.:/var/www/html'
      networks:
        - recipynet
      depends_on:
        - mysql
        - meilisearch
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3521:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'recipyuserpw'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'recipy'
            MYSQL_USER: 'recipyuser'
            MYSQL_PASSWORD: 'recipyuserpw'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'recipy-mysql:/var/lib/mysql'
        networks:
            - recipynet
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '3522:7700'
        volumes:
            - 'recipy-meilisearch:/meili_data'
        networks:
            - recipynet
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:3522/health"]
            retries: 3
            timeout: 5s
networks:
    recipynet:
        driver: bridge
volumes:
    recipy-mysql:
        driver: local
    recipy-meilisearch:
        driver: local
